apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: redis # {"$kpt-set":"namespace"}
  labels:
    app: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
      - name: redisinsight
        image: redislabs/redisinsight
        imagePullPolicy: Always
        volumeMounts:
        - name: db #Pod volumes to mount into the container's filesystem. Cannot be updated.
          mountPath: /db
        ports:
        - containerPort: 8003 # {"$kpt-set":"redisinsight-port"}
          protocol: TCP
      volumes:
      - name: db
        emptyDir: {}
