apiVersion: redis.kun/v1beta1
kind: RedisCluster
metadata:
  name: redis # {"$kpt-set":"cluster-name"}
  namespace: redis # {"$kpt-set":"namespace"}
spec:
  size: 3 # {"$kpt-set":"replica-size"}
  # Leave empty if you don't want to set password
  password: "test" # {"$kpt-set":"password"}
  image: redis:5.0.4-alpine
  monitor:
    image: oliver006/redis_exporter
  # change the configurations
  config:
    loglevel: debug
  monitor:
    image: oliver006/redis_exporter
  # Set to false to add persistence to Redis data.
  disablePersistence: false
  storage:
    # By default, the persistent volume claims will be deleted when the Redis Cluster be delete.
    # If this is not the expected usage, a keepAfterDeletion flag can be added under the storage section
    keepAfterDeletion: true # {"$kpt-set":"keep-after-deletion"}
    persistentVolumeClaim:
      metadata:
        name: redis # {"$kpt-set":"pvc"}
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: redis # {"$kpt-set":"storage-class"}
        resources:
          requests:
            storage: 20Gi # {"$kpt-set":"storage-size"}
