apiVersion: v1
kind: Namespace
metadata:
  name: redis # {"$kpt-set":"namespace"}
  labels:
    name: redis-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator
  namespace: redis # {"$kpt-set":"namespace"}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-operator
  template:
    metadata:
      labels:
        name: redis-operator
    spec:
      serviceAccountName: redis-operator
      containers:
      - name: redis-operator
        # Replace this with the built image name
        image: fishu/redis-operator:latest
        command:
        - redis-operator
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "redis-operator"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-operator
  namespace: redis # {"$kpt-set":"namespace"}
subjects:
- kind: ServiceAccount
  name: redis-operator
  namespace: redis # {"$kpt-set":"namespace"}
roleRef:
  kind: Role
  name: redis-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis-operator
  namespace: redis # {"$kpt-set":"namespace"}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - endpoints
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resourceNames:
  - redis-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - redis.kun
  resources:
  - '*'
  verbs:
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-operator
  namespace: redis # {"$kpt-set":"namespace"}
