apiVersion: v1
kind: Namespace
metadata:
  name: redis # {"$kpt-set":"namespace"}
  labels:
    name: redis-operator # {"$kpt-set":"name"}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-operator # {"$kpt-set":"name"}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator # {"$kpt-set":"name"}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-operator # {"$kpt-set":"name"}
  template:
    metadata:
      labels:
        name: redis-operator # {"$kpt-set":"name"}
    spec:
      serviceAccountName: redis-operator # {"$kpt-set":"name"}
      containers:
      - name: redis-operator # {"$kpt-set":"name"}
        # Replace this with the built image name
        image: fishu/redis-operator:latest
        command:
        - redis-operator # {"$kpt-set":"name"}
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "redis-operator"
